[all:vars]
ansible_user=user7
ansible_ssh_private_key_file=/home/user/.ssh/yc_ed25519
# Проксирование SSH через Bastion для хостов в приватной сети
ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -q user7@51.250.87.80"'

[webservers]
web-server-a ansible_host=10.20.1.31
web-server-b ansible_host=10.20.2.27


[grafana]
grafana-server ansible_host=10.10.1.8

[elasticsearch]
elasticsearch-server ansible_host=10.20.1.17

[kibana]
kibana-server ansible_host=10.10.1.31

[prometheus]
prometheus-server ansible_host=10.20.1.24
