input {
  beats {
    port => 5044
  }
}

filter {
  grok {
    match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp}\] %{LOGLEVEL:log_level}: Пользователь %{WORD:username} вошел успешно с IP %{IP:client_ip}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "custom-app-logs-%{+YYYY.MM.dd}"
  }
}
