version: '3.8'

services:
  pushgateway:
    image: prom/pushgateway:latest
    container_name: chet-i-s-netology-pushgateway
    ports:
      - "9091:9091"
    volumes:
      - pushgateway_data:/data
    restart: unless-stopped

volumes:
  pushgateway_data:
