[webservers]
web-a ansible_host=10.0.2.19
web-b ansible_host=10.0.2.24
db-server ansible_host=10.0.2.3

[webservers:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/ed25519
# Добавляем StrictHostKeyChecking=no, чтобы не чистить known_hosts вручную
ansible_ssh_common_args='-o ProxyJump=ubuntu@111.88.241.116 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

[all:vars]
ansible_python_interpreter=/usr/bin/python3
