---
- name: Change system motd (Message of the Day)
  hosts: webservers
  become: yes
  vars:
    custom_motd: |
      ______________________________________
      |                                      |
      |   Welcome to the Custom Ansible MOTD |
      |   System managed by Ansible          |
      |   Last updated: {{ ansible_date_time.iso8601 }} |
      |______________________________________|

  tasks:
    - name: Update /etc/motd
      ansible.builtin.copy:
        dest: /etc/motd
        content: "{{ custom_motd }}"
        mode: '0644'
