---
- name: Change system motd
  hosts: webservers
  become: yes
  tasks:
    - name: Update /etc/motd
      ansible.builtin.copy:
        dest: /etc/motd
        content: |
          ______________________________________

          Welcome to {{ ansible_hostname }}!
          Server IP: {{ ansible_default_ipv4.address | default(ansible_host) }}

          Have a great day, System Administrator!
          ______________________________________
          Last updated: {{ ansible_date_time.iso8601 }}
        mode: '0644'
